//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_cardapio
    {
        public int item_cardapio1 { get; set; }
        public int idcardapio { get; set; }
        public int idproduto { get; set; }
    
        public virtual cardapio cardapio { get; set; }
        public virtual produto produto { get; set; }
    }
}
