//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int cod { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
    }
}
